# Generated by Django 3.2.12 on 2022-02-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_auto_20220224_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epic',
            options={'verbose_name': '任务组', 'verbose_name_plural': '任务组'},
        ),
        migrations.AlterModelOptions(
            name='kanban',
            options={'ordering': ('rank',), 'verbose_name': '看板', 'verbose_name_plural': '看板'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='projectusersetting',
            options={'verbose_name': '项目用户设置', 'verbose_name_plural': '项目用户设置'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('rank',), 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AddField(
            model_name='task',
            name='rank',
            field=models.FloatField(default=0.0, verbose_name='排序参考值'),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='rank',
            field=models.FloatField(default=0.0, verbose_name='排序参考值'),
        ),
    ]
