# Generated by Django 3.2.12 on 2022-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_auto_20220227_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('kanban__rank', 'rank'), 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterField(
            model_name='kanban',
            name='rank',
            field=models.FloatField(blank=True, verbose_name='排序参考值'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rank',
            field=models.FloatField(blank=True, verbose_name='排序参考值'),
        ),
    ]
