# Generated by Django 3.2.12 on 2022-02-27 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_auto_20220227_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='报告人'),
        ),
    ]
