version: '3'

services:
  app:
    image: 'ccr.ccs.tencentyun.com/aweffr-main/gy-jira-backend:0.1'
    restart: always
    volumes:
      - './jira_backend/.env:/app/gy-jira-backend/jira_backend/.env:ro'
      - './logs:/app/gy-jira-backend/logs'
      - './api/media:/app/gy-jira-backend/api/media'
      - './api/static:/app/gy-jira-backend/api/static'
    ports:
      - '8000:8000'


